### ISSUE TITLE
Host documentation

### ISSUE THREAD

**Issue by cako** [PyLops/curvelops#13]
Description
=========
Currently, the documentation must be built locally by the developer. This is not the ideal solution; the documentation should be easily accessible via website.

What done means
==============
A hosted webpage containing the documentation.

**Comment by mrava87** [comment]
Perfect, let me reply here then I merge:

For GitHub pages this is how I set it up for PyMarchneko: https://github.com/DIG-Kaust/pymarchenko/blob/main/Makefile (see the last two commands and this https://github.com/DIG-Kaust/pymarchenko/blob/main/docssrc/Makefile

The assumption here is that you cannot build the doc anywhere but locally (so not even with a GitHub action, which I think is the case for curvelops since we can’t really download the Curvelets code in CI). Also this isn’t really my own solution, I found it somewhere online but it has worked well for me :)

The other step is to go to Settings -> Pages of this repo and select Deploy from a branch and choose the gh-pages

**Comment by cako** [comment]
See https://pylops.github.io/curvelops/contributing.html#contributing-documentation :)

**Comment by mrava87** [comment]
Yay! Nice, well done :)
