### ISSUE TITLE
Memory Leak! 

### ISSUE THREAD

**Issue by hexiangdong2017** [PyLops/curvelops#2]
When I used the curvelops in a loop, I found the memory used by the program was increasing rapidly. I try to delete python object and gc.collect(), but useless. Therefore, has it bugs about memory leak? @cako

**Comment by hexiangdong2017** [comment]
@mrava87

**Comment by mrava87** [comment]
@cako

**Comment by mrava87** [comment]
Thanks for reporting this. We did some test as a previously developed version was leaking memory but actually we never saw this behavior here, it’s a bit surprising. I pinged @cako as he wrote this code and may be able to say more. If you copy-paste your code that would help us troubleshoot

**Comment by cako** [comment]
Hi @hexiangdong2017, thanks for reporting. Following @mrava87, could you please share a snippet of the offending code?

**Comment by hexiangdong2017** [comment]
@cako @mrava87 
You can see my project in https://gitee.com/hexiangdong2019/curve-edge. And can run optimize.py. You can find the memory used by it increasing and not decreased after one iteration.

**Comment by hexiangdong2017** [comment]
Therefore, when the iteration becomes larger, it can't finish. I want to use this library in deep learning as preprocessing, but this bug prevent this.

**Comment by cako** [comment]
Thank you @hexiangdong2017, I haven't been able to get to this yet, but I will make an effort to have a look at it asap!

**Comment by hexiangdong2017** [comment]
Has any progress or planning recently? @cako

**Comment by cako** [comment]
Hi @hexiangdong2017, thanks again for reporting this and sorry for taking so long to address the issue. Profiling these kinds of bindings are quite tough!

I managed to run your code through a profiler, like this:

```bash
mprof run --include-children python optimize.py
mprof plot --flame -o plot.png
```
For testing, I used `maxfev = 100` on the call to `pdfo` to make it faster, I think it should be alright. Running these gives me a linearly increasing memory profile:

![FDCT original short](https://imgur.com/WPdubg5.png)

Then, I changed your code in `eval.py` to remove any call to FDCT and setting `out = img`. This gave me the following profile:

![No FDCT original short](https://imgur.com/9yYLBTW.png)

It's much faster, but more importantly, it is not linearly increasing. So clearly the FDCT codes are leaking memory.

After a lot of research and testing, I believe the problem is that NumPy is not taking ownership of the arrays created by CurveLab. This was a bug in the original code that stemmed from my own misunderstanding of how pybind11 (what I use to wrap the C++ code) worked. So, to fix it, I used a technique that attaches a cleanup function to the NumPy array. When the array gets destroyed, the function is now called to deallocate the memory. Running the test again gives me the following profile:

![FDCT fixed short](https://imgur.com/sQVFnWW.png)


To finalize the test, I ran your `optimize.py` with the original `maxfev = 2700`, which gave me this profile:

![FDCT fixed full](https://imgur.com/UqmIWZS.png)


Success!
